name: Unity Build Chop Chop

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: UOP1_Project/Library
          key: Library-ChopChop-${{ runner.os }}-${{ hashFiles('UOP1_Project/Packages/manifest.json') }}
          restore-keys: |
            Library-ChopChop-${{ runner.os }}-
            Library-ChopChop-
            Library-

      - name: Run Unity tests
        uses: game-ci/unity-test-runner@v4
        id: tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: UOP1_Project
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test results
          path: artifacts

      - name: Build game
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: UOP1_Project
          targetPlatform: StandaloneWindows64

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{ github.run_number }}
          path: build
